version: 2

sources:
  - name: dbtone
    database: HRMS
    schema: HR
    tables:
      - name: EMPLOYEES
      - name: DEPARTMENTS
      - name: JOBS

  - name: dbtone_parque
    database: HRMS
    schema: PARQUE_DBT
    tables:
      - name: ORDERS
      - name: PRODUCTS
      - name: REVIEWS
      - name: USERS
    
